config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :posts, only: %i[index show] do
    resources :comments, only: %i[new create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :content, presence: true

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :content, presence: true
  validates :url, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :nickname, presence: true, length: { maximum: 50 }, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
  # For additional fields in app/views/devise/registrations/new.html.erb
  devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post, only: %i[new create]

  def new
    # @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.post = @post
    @comment.user = current_user
    if @comment.save
      # redirect_to restaurant_path(@post)
      redirect_to post_path(@post), notice: 'Comment was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end

  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new # Pour le formulaire de création de commentaire
    @comments = @post.comments.order(created_at: :desc) # Récupère tous les commentaires associés au post
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/OLD_new.html.erb
<!-- app/views/comments/new.html.erb -->
<div class="container">
  <h1>Create a new comment</h1>

  <%= simple_form_for([@post, @comment], url: post_comments_path(@post)) do |form| %>
    <%# form.error_notification %>

    <%= form.input :content, label: "Content" %>

    <div class="actions">
      <%= form.button :submit, "Create comment", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSharePosts</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <%= favicon_link_tag 'favicon.ico' %>

  </head>

  <body><%= render "shared/navbar" %>
  <%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1689421755150-9c3b8dc3a45b?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D);">
  <div class="container">
    <h1 class="banner-title"><strong>Welcome</strong> to <strong>PerspectiveShare</strong>!</h1>
    <p class="banner-p">Sharing Visions, Shaping Perspectives.</p>
    <%= link_to "GET STARTED", posts_path, class: "btn btn-gradient" %>
   </div>
</div>


<div class="mb-5"></div>
<div class="container p-50">

    <p>Welcome to our platform dedicated to the exchange of information and ideas through shared articles!</p>
    <p>We invite you to explore our articles and participate in the discussion by leaving your comments and reflections. Your contribution is invaluable in enriching conversations and broadening our collective understanding of the topics at hand.</p>
    <p>We would like to remind all our users of the importance of respect and courtesy in our exchanges. We encourage constructive and respectful discussions where everyone can express their opinions openly and kindly towards other members of our community.
    <p>Thank you for being part of our community!</p>


</div>

app/views/posts/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1689421755150-9c3b8dc3a45b?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D);">


  <div class="container">
    <h1 class="color-font-white">Explore our posts</h1>

    <% @posts.each do |post| %>
      <div class="card-index-post">

        <h2></p><%= post.title %></h2>
        <p style="font-style: italic;">Posted by: <%= post.user.nickname %></p>
        <p><%= truncate(post.content, length: 450) %>...</p>

        <%= link_to "Read more", post_path(post.id), class: "btn btn-gradient" %>

      </div>
    <% end %>

  </div>
</div>

app/views/posts/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1689421755150-9c3b8dc3a45b?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D);">

  <!-- app/views/posts/show.html.erb -->
  <div class="container">
    <div class="card-index-post">
      <h1><%= @post.title %></h1>
      <p style="font-style: italic;">Posted by: <%= @post.user.nickname %></p>
      <p><%= @post.content %></p>
      <p style="font-style: italic;">Url: <a href="<%= @post.url %>"><%= @post.url %></a></p>
    </div>


    <% if @comments.any? %>
      <!-- Afficher les commentaires existants -->
      <div class="card-index-post">
        <h1>Comments</h1> <%# ATTENTION - besoin si comment = faire un if%>
        <% @comments.each do |comment| %>
          <div class="comment">
            <p><strong><%= comment.user.nickname %>:</strong> <%= comment.content %></p>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

    <!-- Formulaire de création de commentaire -->
    <%# render 'comments/form', post: @post, comment: @comment %>
    <%= render 'shared/comment_form_new'%>
  </div>

</div>

app/views/shared/_comment_form_new.erb
<!-- app/views/comments/new.html.erb -->
<div class="container">
  <div class="card-index-post">

    <h1>Create a new comment</h1>

    <%= simple_form_for([@post, @comment], url: post_comments_path(@post)) do |form| %>
      <%# form.input :content, label: "Content" %>
      <%= form.text_area :content, label: "Content", class: "form-control light-gray-background margin-text-area", rows: 5 %>
      <%= form.button :submit, "Create", class: "btn btn-gradient" %>
    <% end %>

  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logoPerspectiveShare.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active" style="margin-right: 20px;">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item" style="margin-right: 20px;">
            <%= link_to "Our posts", posts_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "Avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%# link_to "Action", "#", class: "dropdown-item" %>
              <%# link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>